version: "3.1" 
services:
  dovecot:
    image: thehelpfulidiot/mbsync:latest
    container_name: mbsync
    volumes:
      - /path/to/mail:/mail
    environment:
      - host_name=server
      - port=port
      - remote_username=username
      - remote_password=password
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=fastmail
